# Generated by Django 5.1.4 on 2025-11-25 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomBanner',
            fields=[
                ('bottombanner_id', models.AutoField(primary_key=True, serialize=False)),
                ('bottombanner_image', models.TextField()),
                ('bottombanner_large_image', models.TextField(blank=True, null=True)),
                ('bottombanner_website', models.TextField(blank=True, null=True)),
                ('bottombanner_order', models.IntegerField(blank=True, null=True)),
                ('bottombanner_status', models.IntegerField(blank=True, default=1, null=True)),
                ('bottombanner_month', models.IntegerField(blank=True, null=True)),
                ('bottombanner_year', models.CharField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'BottomBanner',
            },
        ),
        migrations.CreateModel(
            name='MiddleBanner',
            fields=[
                ('middlebanner_id', models.AutoField(primary_key=True, serialize=False)),
                ('middlebanner_image', models.TextField()),
                ('middlebanner_month', models.IntegerField(blank=True, null=True)),
                ('middlebanner_year', models.CharField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'MiddleBanner',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('topbanner_id', models.AutoField(primary_key=True, serialize=False)),
                ('topbanner_image', models.TextField()),
                ('topbanner_large_image', models.TextField(blank=True, null=True)),
                ('topbanner_website', models.TextField(blank=True, null=True)),
                ('topbanner_order', models.IntegerField(blank=True, null=True)),
                ('topbanner_status', models.IntegerField(blank=True, default=1, null=True)),
                ('topbanner_month', models.IntegerField(blank=True, null=True)),
                ('topbanner_year', models.CharField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TopBanner',
            },
        ),
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(blank=True, max_length=500, null=True)),
                ('event_details', models.TextField(blank=True, null=True)),
                ('event_status', models.IntegerField(blank=True, default=1, null=True)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_month', models.IntegerField(blank=True, null=True)),
                ('event_year', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventManagement',
            },
        ),
    ]
